//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupervisorMobility.Client.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SupervisorMobility.Client.Data.Resources.Resource2", typeof(Resource2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string area {
            get {
                return ResourceManager.GetString("area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        public static string attendance {
            get {
                return ResourceManager.GetString("attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compas.
        /// </summary>
        public static string compas {
            get {
                return ResourceManager.GetString("compas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution.
        /// </summary>
        public static string distribution {
            get {
                return ResourceManager.GetString("distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string group {
            get {
                return ResourceManager.GetString("group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has.
        /// </summary>
        public static string has {
            get {
                return ResourceManager.GetString("has", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Personal Found.
        /// </summary>
        public static string no_personal_found {
            get {
                return ResourceManager.GetString("no personal found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.
        /// </summary>
        public static string payroll {
            get {
                return ResourceManager.GetString("payroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select filters.
        /// </summary>
        public static string please_select_filters {
            get {
                return ResourceManager.GetString("please select filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Attendance.
        /// </summary>
        public static string save_attendance {
            get {
                return ResourceManager.GetString("save attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a SSV.
        /// </summary>
        public static string select_a_ssv {
            get {
                return ResourceManager.GetString("select a ssv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        public static string station {
            get {
                return ResourceManager.GetString("station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subordinates.
        /// </summary>
        public static string subordinates {
            get {
                return ResourceManager.GetString("subordinates", resourceCulture);
            }
        }
    }
}
