//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupervisorMobility.Client.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SupervisorMobility.Client.Data.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operator.
        /// </summary>
        public static string _operator {
            get {
                return ResourceManager.GetString("operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All SSV.
        /// </summary>
        public static string allSSV {
            get {
                return ResourceManager.GetString("allSSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All Status.
        /// </summary>
        public static string allStatus {
            get {
                return ResourceManager.GetString("allStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All Supervisors.
        /// </summary>
        public static string allSupervisors {
            get {
                return ResourceManager.GetString("allSupervisors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area.
        /// </summary>
        public static string area {
            get {
                return ResourceManager.GetString("area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attendance.
        /// </summary>
        public static string attendance {
            get {
                return ResourceManager.GetString("attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Authenticating.
        /// </summary>
        public static string authenticating {
            get {
                return ResourceManager.GetString("authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuration.
        /// </summary>
        public static string configuration {
            get {
                return ResourceManager.GetString("configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create new job observation.
        /// </summary>
        public static string createJobObservation {
            get {
                return ResourceManager.GetString("createJobObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the active directory user name..
        /// </summary>
        public static string enterTheActiveDirectoryUserName {
            get {
                return ResourceManager.GetString("enterTheActiveDirectoryUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finished.
        /// </summary>
        public static string finished {
            get {
                return ResourceManager.GetString("finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finished Job Observation.
        /// </summary>
        public static string finishedJobObservation {
            get {
                return ResourceManager.GetString("finishedJobObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First Select an Area.
        /// </summary>
        public static string firstSelectAnArea {
            get {
                return ResourceManager.GetString("firstSelectAnArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First Select an SSV.
        /// </summary>
        public static string firstSelectAnSSV {
            get {
                return ResourceManager.GetString("firstSelectAnSSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First Select a Plant.
        /// </summary>
        public static string firstSelectAPlant {
            get {
                return ResourceManager.GetString("firstSelectAPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Group.
        /// </summary>
        public static string group {
            get {
                return ResourceManager.GetString("group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guides.
        /// </summary>
        public static string guides {
            get {
                return ResourceManager.GetString("guides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In Progress.
        /// </summary>
        public static string inProgress {
            get {
                return ResourceManager.GetString("inProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Job Observation In Progress.
        /// </summary>
        public static string jobObservationInProgress {
            get {
                return ResourceManager.GetString("jobObservationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Job Observations.
        /// </summary>
        public static string jobObservations {
            get {
                return ResourceManager.GetString("jobObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Job Observation Schedule.
        /// </summary>
        public static string jobObservationSchedule {
            get {
                return ResourceManager.GetString("jobObservationSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Late.
        /// </summary>
        public static string late {
            get {
                return ResourceManager.GetString("late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log out.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Month / year.
        /// </summary>
        public static string monthYear {
            get {
                return ResourceManager.GetString("monthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Need Help Navigating?.
        /// </summary>
        public static string needHelpNavigating {
            get {
                return ResourceManager.GetString("needHelpNavigating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plan job observation.
        /// </summary>
        public static string planJobObservation {
            get {
                return ResourceManager.GetString("planJobObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Planned.
        /// </summary>
        public static string planned {
            get {
                return ResourceManager.GetString("planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Planned Job Observation.
        /// </summary>
        public static string plannedJobObservation {
            get {
                return ResourceManager.GetString("plannedJobObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Planned with SSV coaching.
        /// </summary>
        public static string plannedWithSSVCoaching {
            get {
                return ResourceManager.GetString("plannedWithSSVCoaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plant.
        /// </summary>
        public static string plant {
            get {
                return ResourceManager.GetString("plant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rejected.
        /// </summary>
        public static string rejected {
            get {
                return ResourceManager.GetString("rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a Group.
        /// </summary>
        public static string selectAGroup {
            get {
                return ResourceManager.GetString("selectAGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select an Area.
        /// </summary>
        public static string selectAnArea {
            get {
                return ResourceManager.GetString("selectAnArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a Plant.
        /// </summary>
        public static string selectAPlant {
            get {
                return ResourceManager.GetString("selectAPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show all Symbols.
        /// </summary>
        public static string showAllSymbols {
            get {
                return ResourceManager.GetString("showAllSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign In.
        /// </summary>
        public static string signIn {
            get {
                return ResourceManager.GetString("signIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SSV / Area no tiene supervisores..
        /// </summary>
        public static string ssvAreaHasNoSupervisors {
            get {
                return ResourceManager.GetString("ssvAreaHasNoSupervisors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SSV has no supervisors..
        /// </summary>
        public static string ssvHasNoSupervisors {
            get {
                return ResourceManager.GetString("ssvHasNoSupervisors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Symbology to be used.
        /// </summary>
        public static string symbologyToBeUsed {
            get {
                return ResourceManager.GetString("symbologyToBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This Week.
        /// </summary>
        public static string thisWeek {
            get {
                return ResourceManager.GetString("thisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Today.
        /// </summary>
        public static string today {
            get {
                return ResourceManager.GetString("today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To do.
        /// </summary>
        public static string toDo {
            get {
                return ResourceManager.GetString("toDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To Do (LUP).
        /// </summary>
        public static string toDoLup {
            get {
                return ResourceManager.GetString("toDoLup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Under Review.
        /// </summary>
        public static string underReview {
            get {
                return ResourceManager.GetString("underReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
