//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupervisorMobility.Client.Data.Resources.SOSHOE.SynopticTableOfControlPoints {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceSTCP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceSTCP() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SupervisorMobility.Client.Data.Resources.SOSHOE.SynopticTableOfControlPoints.Reso" +
                            "urceSTCP", typeof(ResourceSTCP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string SCPApproved {
            get {
                return ResourceManager.GetString("SCPApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By.
        /// </summary>
        public static string SCPApprovedBy {
            get {
                return ResourceManager.GetString("SCPApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string SCPchange {
            get {
                return ResourceManager.GetString("SCPchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Prod. And Conditions.
        /// </summary>
        public static string SCPCheckProdAndCond {
            get {
                return ResourceManager.GetString("SCPCheckProdAndCond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Points.
        /// </summary>
        public static string SCPControlPoints {
            get {
                return ResourceManager.GetString("SCPControlPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        public static string SCPDate {
            get {
                return ResourceManager.GetString("SCPDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree Of Importance.
        /// </summary>
        public static string SCPDegreeOfImportance {
            get {
                return ResourceManager.GetString("SCPDegreeOfImportance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model(s).
        /// </summary>
        public static string SCPModels {
            get {
                return ResourceManager.GetString("SCPModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string SCPMonth {
            get {
                return ResourceManager.GetString("SCPMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string SCPNo {
            get {
                return ResourceManager.GetString("SCPNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Plant.
        /// </summary>
        public static string SCPnotPlant {
            get {
                return ResourceManager.GetString("SCPnotPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observations.
        /// </summary>
        public static string SCPObservations {
            get {
                return ResourceManager.GetString("SCPObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Observations.
        /// </summary>
        public static string SCPOperationObservations {
            get {
                return ResourceManager.GetString("SCPOperationObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Record.
        /// </summary>
        public static string SCPOperatorRecord {
            get {
                return ResourceManager.GetString("SCPOperatorRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant.
        /// </summary>
        public static string SCPPlant {
            get {
                return ResourceManager.GetString("SCPPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepared By.
        /// </summary>
        public static string SCPPreparedBy {
            get {
                return ResourceManager.GetString("SCPPreparedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string SCPProcess {
            get {
                return ResourceManager.GetString("SCPProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewed By.
        /// </summary>
        public static string SCPReviewedBy {
            get {
                return ResourceManager.GetString("SCPReviewedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor Confirmation.
        /// </summary>
        public static string SCPSupervisorConfirmation {
            get {
                return ResourceManager.GetString("SCPSupervisorConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor Record.
        /// </summary>
        public static string SCPSupervisorRecord {
            get {
                return ResourceManager.GetString("SCPSupervisorRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synoptic Table Of Control Points.
        /// </summary>
        public static string titleSynopticTableOfControlPoints {
            get {
                return ResourceManager.GetString("titleSynopticTableOfControlPoints", resourceCulture);
            }
        }
    }
}
