//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupervisorMobility.Client.Data.Resources.SOSHOE.SynopticTableofOperatingRequirements {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceSTOR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceSTOR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SupervisorMobility.Client.Data.Resources.SOSHOE.SynopticTableofOperatingRequireme" +
                            "nts.ResourceSTOR", typeof(ResourceSTOR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By.
        /// </summary>
        internal static string STORApproved {
            get {
                return ResourceManager.GetString("STORApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string STORChange {
            get {
                return ResourceManager.GetString("STORChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Established Conditions.
        /// </summary>
        internal static string STORConditions {
            get {
                return ResourceManager.GetString("STORConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string STORDate {
            get {
                return ResourceManager.GetString("STORDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string STORDepartment {
            get {
                return ResourceManager.GetString("STORDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree Of Difficulty.
        /// </summary>
        internal static string STORDifficulty {
            get {
                return ResourceManager.GetString("STORDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge.
        /// </summary>
        internal static string STORKnowledge {
            get {
                return ResourceManager.GetString("STORKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning Time.
        /// </summary>
        internal static string STORLearningTime {
            get {
                return ResourceManager.GetString("STORLearningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string STORNumber {
            get {
                return ResourceManager.GetString("STORNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        internal static string STOROperations {
            get {
                return ResourceManager.GetString("STOROperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Machine.
        /// </summary>
        internal static string STORPerMachine {
            get {
                return ResourceManager.GetString("STORPerMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Person.
        /// </summary>
        internal static string STORPerPerson {
            get {
                return ResourceManager.GetString("STORPerPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant.
        /// </summary>
        internal static string STORPlant {
            get {
                return ResourceManager.GetString("STORPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepared By.
        /// </summary>
        internal static string STORPrepared {
            get {
                return ResourceManager.GetString("STORPrepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name.
        /// </summary>
        internal static string STORProcessName {
            get {
                return ResourceManager.GetString("STORProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Assurance Characteristics.
        /// </summary>
        internal static string STORQuality {
            get {
                return ResourceManager.GetString("STORQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewed By.
        /// </summary>
        internal static string STORReviewed {
            get {
                return ResourceManager.GetString("STORReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rev.
        /// </summary>
        internal static string STORRevNumber {
            get {
                return ResourceManager.GetString("STORRevNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet.
        /// </summary>
        internal static string STORSheet {
            get {
                return ResourceManager.GetString("STORSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        internal static string STORSkills {
            get {
                return ResourceManager.GetString("STORSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOS No..
        /// </summary>
        internal static string STORSOSNumber {
            get {
                return ResourceManager.GetString("STORSOSNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synoptic Table Of Operating Requirements.
        /// </summary>
        internal static string STORTable {
            get {
                return ResourceManager.GetString("STORTable", resourceCulture);
            }
        }
    }
}
